---
- name: logiciels communs
  apt: name={{item}} state=present
  with_items:
    - audacity
    - vlc
    - gimp
    - inkscape
    - stellarium
    - chromium
    - gcompris
  become: true

- name: logiciels math
  apt: name={{item}} state=present
  with_items:
    - scratch
    - geogebra
  become: true
