---
- name: remove useless packages
  apt: name={{ item }} state=absent
  with_items:
    - thunderbird
    - xfburn
    - transmission-common
    - pidgin
    - parole
    - simple-scan
    - gnome-mines
    - gmusicbrowser

- name: mise à jour du systeme
  apt: update_cache=yes upgrade=dist
